hubot:
    build: .
    volumes:
       - ./scripts:/home/docker/scripts # copy scripts folder into container
    environment:
        - HUBOT_SLACK_TOKEN=<your team's token>
    links:
        - redis
    restart: always

redis:
    image: redis
    ports:
        - "6379:6379"
